pipeline {
    agent any
    environment {
        PATH = "${PATH}:${getTerraformPath()}"
    }
    stages{
        stage('terraform init'){
            steps {
                slackSend (color: '#FFFF00', message: "STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                dir('CLIXX') {
                    sh "terraform init"
                }
            }
        }
        stage('terraform plan'){
            steps {
                dir('CLIXX') {
                    sh "terraform plan -out=tfplan -input=false"
                }
            }
        }
        stage('Final Deployment Approval') {
            steps {
                script {
                    def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
                }
            }
        }
        stage('Terraform ACTION'){
            steps {
                dir('CLIXX') {
                    sh "terraform ${env.ACTION} --auto-approve tfplan"
                }
            }
        }
    }
}
def getTerraformPath(){
    def tfHome= tool name: 'terraform-14', type: 'terraform'
    return tfHome
}
